name: Lint
on: pull_request
jobs:
  golangci:
    name: Run linters
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Restore cache
        uses: actions/cache@v2
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
      - name: Run linters
        uses: golangci/golangci-lint-action@v2
        with:
          version: latest
          args: -E goimports --timeout 5m0s