name: Test
on: push
jobs:
  unit:
    name: Unit tests
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go
      uses: actions/setup-go@v1
      with:
        go-version: '1.16.3'
    - name: Checkout
      uses: actions/checkout@v2
    - name: Restore cache
      uses: actions/cache@v2
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
    - name: Run tests
      run: |
        make test
